Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ponto_digital_final.Models;
using ponto_digital_final.Repositorios;

namespace ponto_digital_final.Controllers
{
    public class LoginController: Controller
    {
        private UsuarioRepositorio usuarioRepositorio = new UsuarioRepositorio();
        public IActionResult Logar(IFormCollection form){
            UsuarioModel usuario = usuarioRepositorio.BuscarPorEmail(form["uname"]);
            if (usuario != null && usuario.Senha.Equals(form["psw"])){
                System.Console.WriteLine("LOGADO!");
                System.Console.WriteLine($"{usuario.ID}\n{usuario.Nome}\n{usuario.Email}\n{usuario.Senha}\n{usuario.DataNascimento.ToShortDateString()}\n{usuario.Admin}");
                HttpContext.Session.SetString("USER_NOME",usuario.Nome);
                HttpContext.Session.SetString("USER_EMAIL",usuario.Email);
                HttpContext.Session.SetString("USER_ADMIN",usuario.Admin.ToString());
            }
            if (usuario != null)
            {
                if (usuario.Admin)
                {
                    return RedirectToAction("Index","Admin");
                    
                }
            return RedirectToAction("Index","Comentarios");
            }else{

            return RedirectToAction("Index","Home");
            }

        }

        public IActionResult Logout(){
            HttpContext.Session.Remove("USER_NOME");
            HttpContext.Session.Remove("USER_EMAIL");
            HttpContext.Session.Clear();

            return RedirectToAction("Index","Home");
        }
        
    }
}

Controllers/Quem_somosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ponto_digital_final.Controllers
{
    public class Quem_somosController: Controller
    {
        public IActionResult Index(){
            ViewData["UserN"] = HttpContext.Session.GetString("USER_NOME");
            ViewData["UserE"] = HttpContext.Session.GetString("USER_EMAIL");
            ViewData["UserA"] = HttpContext.Session.GetString("USER_ADMIN");
            ViewData["Css"] = "QuemSomos";
            ViewData["Title"] = "Quem Somos?";
            return View();
        }
    }
}

Views/Shared/_AdminLayout.cshtml
@{
    string css = (string) ViewData["Css"];
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>PONTO DIGITAL - ADMIN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/css/admin.css">   
    @if (css.Equals("Aprovacao"))
    {
        <link rel="stylesheet" href="~/css/admin_aprovar.css">           
    }else if (css.Equals("Admin"))
    {
        <link rel="stylesheet" href="~/css/admin_home.css">           
    }else if (css.Equals("Usuarios"))
    {
        <link rel="stylesheet" href="~/css/admin_usuarios.css">           
        
    }else if (css.Equals("Comentarios"))
    {
        <link rel="stylesheet" href="~/css/admin_comentarios.css">           
        
    }else if (css.Equals("Editar"))
    {
        <link rel="stylesheet" href="~/css/admin_editar.css">           
        
    }

</head>
<body>
    <h1>PONTO DIGITAL</h1>
    <header>
        <div id="div_menu">
            <span class="botao_menu"><img src="~/img/icone-sandwich.png" alt="Icone Menu"></span>
            <nav id="menu" class="menu">
                <ul class="ul_menu">
                    <li><a href='@Url.Action("Index", "Home")'>Home</a></li>
                    <li><a href='@Url.Action("Index", "Admin")'>Home Admin</a></li>
                    <li><a href='@Url.Action("Comentarios", "Admin")'>Gerenciar Comentários</a></li>
                    <li><a href='@Url.Action("Usuarios", "Admin")'>Gerenciar Usuários</a></li>
                    <li><a href='@Url.Action("Logout", "Login")' >Logout</a></li>
                 </ul>
            </nav>
        </div>
    </header>


@RenderBody()

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(function() {
            var nav = $('.menu');
            var botao = $('.botao_menu');
            botao.on('click',function(){
                nav.toggleClass('active');
            });
        });
    </script>


</body>
</html>

Views/Shared/_Layout.cshtml
@{
    var user = (string) ViewData["UserN"];
    var admin = (string) ViewData["UserA"];
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PONTO DIGITAL - @ViewData["Title"].ToString().ToUpper()</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/login.css">
    @if (ViewData["Css"].Equals("Home"))
    {
        <link rel="stylesheet" href="css/home.css">
    }else if (ViewData["Css"].Equals("Comentarios"))
    {
        <link rel="stylesheet" href="css/comentarios.css">
    }else if (ViewData["Css"].Equals("Cadastro"))
    {
        <link rel="stylesheet" href="css/cadastro.css">
    }else if (ViewData["Css"].Equals("Planos"))
    {
        <link rel="stylesheet" href="css/planos.css">     
        <link rel="stylesheet" href="css/popup_planos.css">  
    }else if (ViewData["Css"].Equals("QuemSomos"))
    {
        <link rel="stylesheet" href="css/quem_somos.css">          
    }else if (ViewData["Css"].Equals("Contatos"))
    {
        <link rel="stylesheet" href="css/contatos.css">                  
    }

    
</head>

<body>
    <header>
        <h1>Ponto Digital</h1>
        <div id="div_menu">
                <span class="botao_menu"><img src="img/icone-sandwich.png" alt="Icone Menu"></span>
            <nav id="menu" class="menu">
                <ul class="ul_menu">
                    <li><a href='@Url.Action("Index", "Home")'>Home</a></li> 
                    <li><a href='@Url.Action("Index", "Planos")' >Planos</a></li>
                    <li><a href='@Url.Action("Index", "Quem_somos")' >Quem somos?</a></li>
                    <li><a href='@Url.Action("Index", "Contatos")' >Contatos</a></li>
                    <li><a href='@Url.Action("Index", "Comentarios")'>Comentários</a></li> 
                    <li><a href='@Url.Action("Index", "Cadastro")' >Cadastro</a></li>
                    @if (!string.IsNullOrEmpty(admin))
                    {
                        @if (admin.Equals("True"))
                        {
                            <li><a href='@Url.Action("Index", "Admin")'>Home Admin</a></li>
                            
                        }
                    }
                    @if (string.IsNullOrEmpty(user))
                    {
                        <p onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</p>
                    }else
                    {
                        <li><a href='@Url.Action("Logout", "Login")' >Logout</a></li>
                    }        
    
                </ul>
            </nav>
        </div>
    </header>

    @RenderBody()


    
    <footer>
        <div id="rodape">
            <div id="contatos">
                <p>Telefone: 94002-8922</p>
                <p>E-mail: pontodigital@gmail.com </p>
                <div>
                    <a href="#"><img src="img/icone-facebook.png" alt="Icone Facebook"> </a>
                    <a href="#"><img src="img/icone-gmail.png" alt="Icone Gmail"> </a>
                </div>
            </div>
            <nav id="menu_pe">
                <ul>
                        <li><a href='@Url.Action("Index", "Home")'>Home</a></li> 
                    <li><a href='@Url.Action("Index", "Planos")' >Planos</a></li>
                    <li><a href='@Url.Action("Index", "Quem_somos")' >Quem somos?</a></li>
                    <li><a href='@Url.Action("Index", "Contatos")' >Contatos</a></li>
                    <li><a href='@Url.Action("Index", "Comentarios")'>Comentários</a></li> 
                    <li><a href='@Url.Action("Index", "Cadastro")' >Cadastro</a></li>
                </ul>
            </nav>
      </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(function() {
            var nav = $('.menu');
            var botao = $('.botao_menu');
            botao.on('click',function(){
                nav.toggleClass('active');
            });
        });
    </script>

<div id="id01" class="modal">
  
    <form class="modal-content animate" method="POST" action='@Url.Action("Logar", "Login")'>
        <div class="imgcontainer">
            <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
            <img src="img/logo/favicon.png" alt="Logo" class="avatar">
        </div>
    
        <div class="container">
            <label for="uname"><b>Email de Usuário:</b></label> <br>
            <input type="text" placeholder="Insira seu email" name="uname" required>
            <br> <br>
            <label for="psw"><b>Senha:</b></label> <br>
            <input type="password" placeholder="Insira sua senha" name="psw" required>
                
            <button type="submit">Acessar</button>
        </div>
        <div id="rodape-login">
        <p>Não tem conta ainda? </p> <a href='@Url.Action("Index", "Cadastro")'> Cadrastre-se já!</a>
        </div>

    </form>
</div>
      
      <script>
        var modal = document.getElementById('id01');
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
      </script>

</body>
</html>